export const countryToFlag = (countryName: string): string => {
  const flags: { [key: string]: string } = {
    // Europa (fortsättning)
    'Sweden': '🇸🇪',
    'Sverige': '🇸🇪',
    'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    'France': '🇫🇷',
    'Frankrike': '🇫🇷',
    'Germany': '🇩🇪',
    'Tyskland': '🇩🇪',
    'Spain': '🇪🇸',
    'Spanien': '🇪🇸',
    'Italy': '🇮🇹',
    'Italien': '🇮🇹',
    'Netherlands': '🇳🇱',
    'Nederländerna': '🇳🇱',
    'Portugal': '🇵🇹',
    'Belgium': '🇧🇪',
    'Belgien': '🇧🇪',
    'Croatia': '🇭🇷',
    'Kroatien': '🇭🇷',
    'Denmark': '🇩🇰',
    'Danmark': '🇩🇰',
    'Norway': '🇳🇴',
    'Norge': '🇳🇴',
    'Finland': '🇫🇮',
    'Switzerland': '🇨🇭',
    'Schweiz': '🇨🇭',
    'Austria': '🇦🇹',
    'Österrike': '🇦🇹',
    'Poland': '🇵🇱',
    'Polen': '🇵🇱',
    'Turkey': '🇹🇷',
    'Turkiet': '🇹🇷',
    'Ukraine': '🇺🇦',
    'Ukraina': '🇺🇦',
    'Czech Republic': '🇨🇿',
    'Tjeckien': '🇨🇿',
    'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    'Hungary': '🇭🇺',
    'Ungern': '🇭🇺',
    'Serbia': '🇷🇸',
    'Serbien': '🇷🇸',
    'Slovenia': '🇸🇮',
    'Slovenien': '🇸🇮',
    'Slovakia': '🇸🇰',
    'Slovakien': '🇸🇰',
    'Romania': '🇷🇴',
    'Rumänien': '🇷🇴',
    'Albania': '🇦🇱',
    'Albanien': '🇦🇱',
    'Georgia': '🇬🇪',
    'Georgien': '🇬🇪',
    'Bosnia and Herzegovina': '🇧🇦',
    'Bosnia': '🇧🇦',
    'Bosnien och Hercegovina': '🇧🇦',
    'Bosnien': '🇧🇦',
    'Iceland': '🇮🇸',
    'Island': '🇮🇸',
    'Greece': '🇬🇷',
    'Grekland': '🇬🇷',

    // Sydamerika (fortsättning)
    'Brazil': '🇧🇷',
    'Brasilien': '🇧🇷',
    'Argentina': '🇦🇷',
    'Uruguay': '🇺🇾',
    'Colombia': '🇨🇴',
    'Chile': '🇨🇱',
    'Ecuador': '🇪🇨',
    'Peru': '🇵🇪',
    'Paraguay': '🇵🇾',
    'Bolivia': '🇧🇴',
    'Venezuela': '🇻🇪',

    // Nord/Centralamerika & Karibien
    'USA': '🇺🇸',
    'Mexico': '🇲🇽',
    'Mexiko': '🇲🇽',
    'Canada': '🇨🇦',
    'Kanada': '🇨🇦',
    'Costa Rica': '🇨🇷',
    'Panama': '🇵🇦',
    'Haiti': '🇭🇹',
    'Jamaica': '🇯🇲',
    'Cuba': '🇨🇺',
    'Kuba': '🇨🇺',

    // Afrika (fortsättning)
    'South Africa': '🇿🇦',
    'Sydafrika': '🇿🇦',
    'Nigeria': '🇳🇬',
    'Senegal': '🇸🇳',
    'Morocco': '🇲🇦',
    'Marocko': '🇲🇦',
    'Egypt': '🇪🇬',
    'Egypten': '🇪🇬',
    'Cameroon': '🇨🇲',
    'Kamerun': '🇨🇲',
    'Ghana': '🇬🇭',
    'Tunisia': '🇹🇳',
    'Tunisien': '🇹🇳',
    'Algeria': '🇩🇿',
    'Algeriet': '🇩🇿',
    'Ivory Coast': '🇨🇮',
    'Elfenbenskusten': '🇨🇮',
    'Cape Verde': '🇨🇻',
    'Cap Verde': '🇨🇻',
    'Kap Verde': '🇨🇻',
    'Mali': '🇲🇱',
    'Burkina Faso': '🇧🇫',
    'Angola': '🇦🇴',

    // Asien & Oceanien
    'Japan': '🇯🇵',
    'South Korea': '🇰🇷',
    'Sydkorea': '🇰🇷',
    'Australia': '🇦🇺',
    'Australien': '🇦🇺',
    'Saudi Arabia': '🇸🇦',
    'Saudiarabien': '🇸🇦',
    'Iran': '🇮🇷',
    'China': '🇨🇳',
    'Kina': '🇨🇳',
    'Qatar': '🇶🇦',
  }

  // Försök hitta exakt matchning eller normaliserad matchning
  const normalized = countryName.trim();
  return flags[normalized] || ''
}
